name: test matrix content 
on: push  
jobs: 
  build: 
    continue-on-error: true
    strategy:
        matrix:         
            node-version: [12,14,16]
            oprating-system: [ubuntu-latest, windows-latest]
            include:
                - node-version:  18
                  oprating-system: ubuntu-latest
        
            exclude:
                - node-version: 12
                  oprating-system: windows-latest                       
    runs-on: ${{ matrix.oprating-system }}
    steps: 
        - name: Git Checkout
          uses: actions/checkout@v4
        - name: Install NodeJs
          uses: actions/setup-node@v4
          with: 
            node-version: ${{ matrix.node-version }}
        - name: install Dependancy 
          run: npm ci
        - name: Build Project
          run: npm run build 
