name: test matrix content 
on: push  
jobs: 
  build: 
    strategy:
        matrix:         
            node-version: [12,14,16]
            oprating-system: [ubuntu-latest]        
    runs-on: ${{ matrix.oprating-system }}
    steps: 
        - name: Git Checkout
          uses: actions/checkout@v4
        - name: Install NodeJs
          uses: actions/setup-node@v4
          with: 
            node-version: ${{ matrix.node-version }}
        - name: install Dependancy 
          run: npm ci
        - name: Build Project
          run: npm run build 
