name: reuse workflow 
on:
 workflow_call:
    inputs: 
      artifact-name:
        required: false
        default: dist-files
        type: string 
jobs: 
    deploy: 
        runs-on: ubuntu-latest
        steps: 
        - name: Download artifacts  
          uses: actions/download-artifact@v4
          with: 
            name: ${{ inputs.artifact-name }}
        - name: List file 
          run: ls 
        - name : use reuseble workflow 
          run: echo "Deployeing ..." 